/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/source/chess_set_4k.gltf -o components/models/ChessSetModel.tsx --types --nocompile 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    piece_rook_white_01: THREE.Mesh
    piece_pawn_white_01: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    piece_queen_white: THREE.Mesh
    piece_king_white: THREE.Mesh
    piece_knight_white_01: THREE.Mesh
    board: THREE.Mesh
    piece_knight_white_02: THREE.Mesh
    piece_rook_white_02: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    piece_pawn_white_02: THREE.Mesh
    piece_pawn_white_03: THREE.Mesh
    piece_pawn_white_04: THREE.Mesh
    piece_pawn_white_05: THREE.Mesh
    piece_pawn_white_06: THREE.Mesh
    piece_pawn_white_07: THREE.Mesh
    piece_pawn_white_08: THREE.Mesh
    piece_rook_black_01: THREE.Mesh
    piece_pawn_black_01: THREE.Mesh
    Cylinder022: THREE.Mesh
    Cylinder022_1: THREE.Mesh
    piece_queen_black: THREE.Mesh
    piece_king_black: THREE.Mesh
    piece_knight_black_01: THREE.Mesh
    piece_knight_black_02: THREE.Mesh
    piece_rook_black_02: THREE.Mesh
    Cylinder025: THREE.Mesh
    Cylinder025_1: THREE.Mesh
    piece_pawn_black_02: THREE.Mesh
    piece_pawn_black_03: THREE.Mesh
    piece_pawn_black_04: THREE.Mesh
    piece_pawn_black_05: THREE.Mesh
    piece_pawn_black_06: THREE.Mesh
    piece_pawn_black_07: THREE.Mesh
    piece_pawn_black_08: THREE.Mesh
  }
  materials: {
    chess_set_pieces_white: THREE.MeshStandardMaterial
    chess_set_board: THREE.MeshStandardMaterial
    chess_set_pieces_black: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chess_set_4k.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.piece_rook_white_01.geometry} material={materials.chess_set_pieces_white} position={[0.203, 0.017, -0.203]} />
      <mesh geometry={nodes.piece_pawn_white_01.geometry} material={materials.chess_set_pieces_white} position={[0.203, 0.017, -0.145]} />
      <group position={[0.087, 0.017, -0.203]}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials.chess_set_pieces_white} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials.chess_set_pieces_white} />
      </group>
      <mesh geometry={nodes.piece_queen_white.geometry} material={materials.chess_set_pieces_white} position={[-0.029, 0.017, -0.203]} />
      <mesh geometry={nodes.piece_king_white.geometry} material={materials.chess_set_pieces_white} position={[0.029, 0.017, -0.203]} />
      <mesh geometry={nodes.piece_knight_white_01.geometry} material={materials.chess_set_pieces_white} position={[0.145, 0.017, -0.203]} />
      <mesh geometry={nodes.board.geometry} material={materials.chess_set_board} />
      <mesh geometry={nodes.piece_knight_white_02.geometry} material={materials.chess_set_pieces_white} position={[-0.145, 0.017, -0.203]} />
      <mesh geometry={nodes.piece_rook_white_02.geometry} material={materials.chess_set_pieces_white} position={[-0.203, 0.017, -0.203]} />
      <group position={[-0.087, 0.017, -0.203]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.chess_set_pieces_white} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.chess_set_pieces_white} />
      </group>
      <mesh geometry={nodes.piece_pawn_white_02.geometry} material={materials.chess_set_pieces_white} position={[0.145, 0.017, -0.145]} />
      <mesh geometry={nodes.piece_pawn_white_03.geometry} material={materials.chess_set_pieces_white} position={[0.087, 0.017, -0.145]} />
      <mesh geometry={nodes.piece_pawn_white_04.geometry} material={materials.chess_set_pieces_white} position={[0.029, 0.017, -0.145]} />
      <mesh geometry={nodes.piece_pawn_white_05.geometry} material={materials.chess_set_pieces_white} position={[-0.029, 0.017, -0.145]} />
      <mesh geometry={nodes.piece_pawn_white_06.geometry} material={materials.chess_set_pieces_white} position={[-0.087, 0.017, -0.145]} />
      <mesh geometry={nodes.piece_pawn_white_07.geometry} material={materials.chess_set_pieces_white} position={[-0.145, 0.017, -0.145]} />
      <mesh geometry={nodes.piece_pawn_white_08.geometry} material={materials.chess_set_pieces_white} position={[-0.203, 0.017, -0.145]} />
      <mesh geometry={nodes.piece_rook_black_01.geometry} material={materials.chess_set_pieces_black} position={[-0.203, 0.017, 0.202]} />
      <mesh geometry={nodes.piece_pawn_black_01.geometry} material={materials.chess_set_pieces_black} position={[-0.203, 0.017, 0.144]} />
      <group position={[-0.087, 0.017, 0.202]}>
        <mesh geometry={nodes.Cylinder022.geometry} material={materials.chess_set_pieces_black} />
        <mesh geometry={nodes.Cylinder022_1.geometry} material={materials.chess_set_pieces_black} />
      </group>
      <mesh geometry={nodes.piece_queen_black.geometry} material={materials.chess_set_pieces_black} position={[-0.029, 0.017, 0.202]} />
      <mesh geometry={nodes.piece_king_black.geometry} material={materials.chess_set_pieces_black} position={[0.029, 0.017, 0.203]} />
      <mesh geometry={nodes.piece_knight_black_01.geometry} material={materials.chess_set_pieces_black} position={[-0.145, 0.017, 0.202]} />
      <mesh geometry={nodes.piece_knight_black_02.geometry} material={materials.chess_set_pieces_black} position={[0.145, 0.017, 0.202]} />
      <mesh geometry={nodes.piece_rook_black_02.geometry} material={materials.chess_set_pieces_black} position={[0.203, 0.017, 0.202]} />
      <group position={[0.087, 0.017, 0.202]}>
        <mesh geometry={nodes.Cylinder025.geometry} material={materials.chess_set_pieces_black} />
        <mesh geometry={nodes.Cylinder025_1.geometry} material={materials.chess_set_pieces_black} />
      </group>
      <mesh geometry={nodes.piece_pawn_black_02.geometry} material={materials.chess_set_pieces_black} position={[-0.145, 0.017, 0.144]} />
      <mesh geometry={nodes.piece_pawn_black_03.geometry} material={materials.chess_set_pieces_black} position={[-0.087, 0.017, 0.144]} />
      <mesh geometry={nodes.piece_pawn_black_04.geometry} material={materials.chess_set_pieces_black} position={[-0.029, 0.017, 0.144]} />
      <mesh geometry={nodes.piece_pawn_black_05.geometry} material={materials.chess_set_pieces_black} position={[0.029, 0.017, 0.144]} />
      <mesh geometry={nodes.piece_pawn_black_06.geometry} material={materials.chess_set_pieces_black} position={[0.087, 0.017, 0.144]} />
      <mesh geometry={nodes.piece_pawn_black_07.geometry} material={materials.chess_set_pieces_black} position={[0.145, 0.017, 0.144]} />
      <mesh geometry={nodes.piece_pawn_black_08.geometry} material={materials.chess_set_pieces_black} position={[0.203, 0.017, 0.144]} />
    </group>
  )
}

useGLTF.preload('/chess_set_4k.gltf')
